image:
  repository: frederikpietzko/spring-boot-jdbc
  tag: 6d574a9

extraEnv:
  - name: SPRING_THREADS_VIRTUAL_ENABLED
    value: "true"
  - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
    value: "100"
