quarkus.application.name=quarkus-jdbi
quarkus.container-image.group=frederikpietzko
quarkus.container-image.name=quarkus-jdbi
quarkus.container-image.tag=${project.version}
quarkus.datasource.jdbc.url=${JDBC_URL:jdbc:postgresql://localhost:6432/postgres?prepareThreshold=0}
quarkus.datasource.username=${DB_USERNAME:pg}
quarkus.datasource.password=${DB_PASSWORD:pg}
quarkus.datasource.jdbc.max-size=100
quarkus.micrometer.export.prometheus.path=/metrics
quarkus.datasource.metrics.enabled=true
