quarkus.application.name=quarkus
quarkus.container-image.group=frederikpietzko
quarkus.container-image.name=quarkus
quarkus.container-image.tag=${project.version}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:6432/postgres?prepareThreshold=0
quarkus.datasource.username=pg
quarkus.datasource.password=pg
quarkus.datasource.jdbc.max-size=100
