micronaut.application.name=micronaut
datasources.default.jdbc-url=jdbc:postgresql://localhost:6432/postgres
micronaut.metrics.export.prometheus.path=/metrics
endpoints.prometheus.enabled=true
endpoints.prometheus.sensitive=false
datasources.default.username=pg
datasources.default.password=pg

