micronaut.application.name=micronaut
datasources.default.jdbc-url=${JDBC_URL:jdbc:postgresql://localhost:6432/postgres}
micronaut.metrics.export.prometheus.path=/metrics
endpoints.prometheus.enabled=true
endpoints.prometheus.sensitive=false
datasources.default.username=${DB_USERNAME:pg}
datasources.default.password=${DB_PASSWORD:pg}

