server:
  port: 8080
  host: 0.0.0.0
  features:
    observe:
      endpoint: "/"
db:
  source: "jdbc"
  connection:
    url: "${JDBC_URL:jdbc:postgresql://localhost:6432/postgres}"
    username: "${DB_USERNAME:pg}"
    password: "${DB_PASSWORD:pg}"
    maximumPoolSize: 100
metrics:
  app-name: helidon-se
