spring:
  application:
    name: spring-boot
  datasource:
    url: "jdbc:postgresql://localhost:6432/postgres?prepareThreshold=0"
    username: "pg"
    password: "pg"
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /
      path-mapping:
        prometheus: metrics
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

