spring:
  application:
    name: spring-boot
  datasource:
    url: "${JDBC_URL:jdbc:postgresql://localhost:6432/postgres?prepareThreshold=0}"
    username: "${DB_USERNAME:pg}"
    password: "${DB_PASSWORD:pg}"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /
      path-mapping:
        prometheus: metrics
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
