javax:
  sql:
    DataSource:
      default:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        maximumPoolSize: 100
        minimumIdle: 20
        dataSource:
          url: "${JDBC_URL:jdbc:postgresql://localhost:6432/postgres}"
          user: "${DB_USERNAME:pg}"
          password: "${DB_PASSWORD:pg}"
hibernate:
  hbm2ddl:
    auto: validate
metrics:
  app-name: helidon-mp
