ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.github.frederikpietzko.AppKt.main
  development: false
  engine:
    threads: 16
    requestQueueLimit: 100
    shareWorkGroup: false
db:
  jdbcUrl: "jdbc:postgresql://localhost:6432/postgres"
  username: "pg"
  password: "pg"
