{{- range $name, $test := .Values.loadtests }}
{{- if $test.enabled }}
---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: {{ include "loadtest.fullname" $ }}-{{ $name }}
  namespace: {{ $.Values.k6.namespace }}
spec:
  parallelism: {{ $test.parallelism | default 1 }}
  script:
    configMap:
      name: {{ $.Release.Name }}-scripts
      file: {{ $test.script }}
  runner:
    nodeSelector:
      pool: {{ $.Values.k6.nodeSelector.pool }}
    env:
      - name: K6_CLOUD_TOKEN
        valueFrom:
          secretKeyRef:
            name: k6-api-token
            key: token
      {{- range $key, $val := $test.env }}
      - name: {{ $key }}
        value: {{ $val | quote }}
      {{- end }}
    arguments:
      - "--out"
      - "cloud"
{{- end }}
{{- end }}
