# Global k6 settings
k6:
  namespace: loadtest
  nodeSelector:
    pool: loadtest

# Subchart configuration
# k6-operator is a dependency, check its values for exact configuration
k6-operator:
  nodeSelector:
    pool: loadtest

# Loadtest definitions
loadtests:
  get-all-visits:
    enabled: true
    script: "loadtest-get-all-visits.js"
    parallelism: 5
    env:
      BASE_URL: "http://benchmark-app-apps.apps.svc.cluster.local:8080"
      PARALLELISM: "5"

  get-visit:
    enabled: false
    script: "loadtest-get-visit.js"
    parallelism: 5
    env:
      BASE_URL: "http://benchmark-app-apps.apps.svc.cluster.local:8080"
      PARALLELISM: "5"

  create-visit:
    enabled: false
    script: "loadtest-create-visit.js"
    parallelism: 5
    env:
      BASE_URL: "http://benchmark-app-apps.apps.svc.cluster.local:8080"
      PARALLELISM: "5"
