micronaut.application.name=micronaut
datasources.default.jdbc-url=jdbc:postgresql://localhost:5432/postgres
datasources.default.username=pg
datasources.default.password=pg
micronaut.metrics.enabled=true
micronaut.metrics.export.prometheus.enabled=true
endpoints.prometheus.enabled=true
endpoints.prometheus.sensitive=false
endpoints.prometheus.path=/metrics
